service: go-serverless-router-example
frameworkVersion: ">=1.28.0 <2.0.0"

provider:
  name: aws
  runtime: go1.x
  stage: ${opt:stage, 'dev'}
  region: us-east-1
  memorySize: 128
  timeout: 10

package:
  exclude:
    - ./**
  include:
    - ./bin/**

functions:
  get:
    handler: "bin/service"
    events:
      - http:
          path:  ""
          method: "get"
  post:
    handler: "bin/service"
    events:
      - http:
          path: ""
          method: post
  anotherGet:
    handler: "bin/service"
    events:
      - http:
          path:  "another"
          method: "get"