[[constraint]]
  name = "github.com/aws/aws-lambda-go"
  version = "1.10.0"

[prune]
  go-tests = true
  unused-packages = true

[[constraint]]
  name = "github.com/stretchr/testify"
  version = "1.3.0"
